version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Weather99
      - MONGO_INITDB_ROOT_PASSWORD=chami1999928
    volumes:
      - mongo-data:/data/db

  backend_new:
    build:
      context: ./backend
    container_name: backend_new
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb+srv://Weather99:chami1999928@weatherdb.kmumq9l.mongodb.net/?retryWrites=true&w=majority
      - NODE_ENV=development
      - JWT_PRIVATE_KEY=jwt-secret
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend_new:
    build:
      context: ./frontend
    container_name: frontend_new
    ports:
      - "3000:80"
    depends_on:
      - backend_new
    volumes:
      - ./frontend:/app

volumes:
  mongo-data:
